import OrderTemplate from './src/main.js'

let template = new OrderTemplate()

let hash = document.location.hash.substr(1)
let input = {
	account: {
		id: 'acqsulrowbxiugvginhw',
		name: 'Subiz',
		logo_url: 'https://vcdn.subiz-cdn.com/file/firegebifshhuufpemtr-mau-logo-tra-sua-dep-va-de-thuong9.jpg',
		logo_url: 'https://subiz.com.vn/blog/wp-content/themes/subiz_blog_2016/images/logo.png',
		owner_id: 'agqygncqpyaxoujpfc',
		state: 'activated',
		confirmed: 0,
		city: 'Hà Nội',
		zip_code: 10000,
		tax_id: '123',
		facebook: 'https://www.facebook.com/subizdotcom/',
		twitter: '',
		phone: '0987814392',
		address: '283 Cầu Giấy,  Hà Nội',
		url: '',
		lang: 'vi',
		timezone: '+07:00',
		country: 'VN',
		date_format: 'YYYY/MM/DD',
		locale: 'vi-VN',
		supported_locales: ['en-US', 'ja-JP', 'vi-VN'],
		currency: 'VND',
	},
	order: {
		account_id: 'acqsulrowbxiugvginhw',
		id: '221098',
		shipping: {
			address: {
				account_id: 'acqsulrowbxiugvginhw',
				user_id: 'usqsxanyuyvykzdcbxnss',
				id: 'adrfidqxbnkajdjbyvxz',
				fullname: 'Hallo',
				email: 'john@yaro.vn',
				phone: '0987814572',
				street: 'Thôn Bùi Xá',
				ward: 'Xã Trung Hòa',
				district: 'Huyện Yên Mỹ',
				address: '187 Thôn Bùi Xá',
				created: 1641793137392,
				created_by: 'agqygncqpyaxoujpfc',
				updated: 1642402820992,
				updated_by: 'agqsulrowbxilyzhds',
				country: 'Việt Nam',
				province: 'Hưng Yên',
				province_id: 'hy',
				district_id: 'hy-ym',
				ward_id: 'hy-ym-wa-th2',
			},
			pickup_address: {
				account_id: 'acqsulrowbxiugvginhw',
				id: 'ghn.2430494',
				fullname: '0974716892',
				phone: '0974716892',
				is_warehouse: true,
				from_shipping_provider: 'ghn',
				from_shipping_shop_id: 'ghn.c94a6718fafe8714a64a9ad3eb6f072b7caf84f7',
				last_integrated: 1642049049873,
				title: '0974716892',
			},
			weight: 1000,
			transport: 'road',
			shipping_provider: 'private',
			pick_amount: 2790000,
			status_code: 'cancel',
			data: {ghtk: {value: 2790000, deliver_option: 'none'}},
			index_incre: 1,
			cancelled_by: 'agqsulrowbxilyzhds',
		},
		status: 'confirmed',
		shipping_status: 'delivery_success',
		payment_status: 'unpaid',
		created: 1642413338363,
		created_by: 'agqsulrowbxilyzhds',
		updated: 1642413427039,
		updated_by: 'agqygncqpyaxoujpfc',
		items: [
			{
				quantity: 1,
				product: {
					account_id: 'acqsulrowbxiugvginhw',
					id: '2110079',
					product_group_id: '2110079',
					left_product_id: '2110079',
					right_product_id: '2110079',
					url: 'https://baohanhone.com/products/man-hinh-apple-watch-s2',
					name: 'Màn Hình Apple Watch S2',
					i18n_name: {vi_VN: 'Màn Hình Apple Watch S2'},
					created: 1637912799417,
					updated: 1637912799417,
					created_by: 'agqsulrowbxilyzhds',
					updated_by: 'agqsulrowbxilyzhds',
					image: 'https://vcdn.subiz-cdn.com/file/firegqkopydrkusdxzzl_acqsulrowbxiugvginhw',
					images: ['https://vcdn.subiz-cdn.com/file/firegqkopydrkusdxzzl_acqsulrowbxiugvginhw'],
					visibility: 'published',
					sku: '1032231',
					price: 2790000,
					stock: 64,
					tax: {
						account_id: 'acqsulrowbxiugvginhw',
						id: 'taregastxfusoaqykqal',
						name: 'V.A.T',
						i18n_name: {en_US: 'GGTT', ja_JP: '付加価値税', th_TH: 'ภาษีมูลค่าเพิ่ม', vi_VN: 'V.A.T', zh_CN: '增值税'},
						percentage: 1000,
						type: 'tax',
						created: 1595816243000,
						created_by: 'agqygncqpyaxoujpfc',
						updated: 1638176240585,
						updated_by: 'agqsulrowbxilyzhds',
					},
				},
				total: 2690000,
				fpv_total: 2690000093184,
				discount_amount: 100000,
				discount_type: 'amount',
				discount_before_tax: true,
				total_tax: 269000,
				fpv_total_tax: 268999999488,
			},
		],
		subtotal: 2690000,
		fpv_subtotal: 2690000093184,
		total: 2919000,
		fpv_total: 2918999916544,
		discount_amount: 20000,
		fpv_discount_amount: 20000000000,
		discount_type: 'amount',
		user: {
			id: 'usqsxanyuyvykzdcbxnss',
			account_id: 'acqsulrowbxiugvginhw',
			attributes: [
				{key: 'phones', text: '87995213'},
				{key: 'first_interact', text: 'start_conversation'},
				{key: 'focused'},
				{key: 'total_sessions', number: 1},
				{key: 'created', datetime: '2020-07-31T07:07:44Z'},
				{key: 'published_seen', datetime: '2020-09-03T02:11:44Z'},
				{key: 'total_conversations', number: 1},
				{key: 'acqsulrowbxiugvginhw_subizv4_subikon', datetime: '2020-07-31T07:07:44Z'},
				{key: 'is_lead', boolean: true},
				{key: 'interacted', datetime: '2020-09-03T02:11:44Z'},
				{key: 'fullname', text: 'Hallo'},
				{key: 'emails', text: 'john@yaro.vn'},
				{key: 'seen', datetime: '2020-09-03T02:11:44Z'},
				{key: 'modified', datetime: '2020-09-03T02:11:44Z'},
				{key: 'latest_session_id', text: 'ssqsxanyzkmrzfdnhedml'},
				{key: 'channel_source', text: 'subizv4.subikon'},
				{key: 'first_session_source', text: 'direct'},
				{key: 'first_session_referer'},
				{key: 'first_session_tracking_link'},
				{key: 'latest_session_source', text: 'direct'},
				{key: 'latest_session_referer'},
				{key: 'latest_session_tracking_link'},
			],
			lead_owners: ['agqsulrpamkxgpqidx', 'agqsulrpcaysnoqnrm', 'agqsulrowbxilyzhds', 'agqsuorpukqwddqrtn'],
			is_lead: true,
		},
		adjustment_description: 'Thanh test',
		adjustment: -20000,
		fpv_adjustment: -20000000000,
		total_tax: 269000,
		fpv_total_tax: 268999999488,
		currency_rate: 1,
	},
	template: {
		primary_color: '#759102',
		secondary_color: 'white',
		font_family: 'Signika',
		number_font_family: 'Signika',
		tagline: 'Strike for inovation',
		i18n_tagline: {
			vi_VN: 'Cải tiến không ngừng',
		},
		terms_and_conditions: 'You must pay before the due date or being charge for 10% per day',
		i18n_terms_and_conditions: {
			vi_VN: 'Bạn phải trả đúng hạn, không thì tính lãi 10% một ngày',
		},
		signature: 'Thanks for buying with us',
		i18n_signature: {
			vi_VN: 'Cảm ơn bạn đã mua hàng',
		},
	},
	locale: 'vi-VN',
}

try {
	if (hash) input = JSON.parse(decodeURIComponent(atob(hash)))
} catch (e) {
	alert('ERR, INVALID HASH')
	console.log('INPUT ERR', e)
}
template.update(input.account, input.order, input.template, input.locale)
template.mount(document.getElementById('app'))
