import OrderTemplate from './index.js'

let template = new OrderTemplate()

let acc = {
	id: 'acqsulrowbxiugvginhw',
	name: 'Infinitea',
	logo_url: 'https://vcdn.subiz-cdn.com/file/firegebifshhuufpemtr-mau-logo-tra-sua-dep-va-de-thuong9.jpg',
	owner_id: 'agqygncqpyaxoujpfc',
	state: 'activated',
	confirmed: 0,
	city: 'Hà Nội',
	zip_code: 10000,
	tax_id: '123',
	facebook: 'https://www.facebook.com/infiniteamilktea/',
	twitter: '',
	phone: '0987814392',
	address: '283 Cầu Giấy,  Hà Nội',
	url: '',
	lang: 'vi',
	timezone: '+07:00',
	country: 'VN',
	date_format: 'YYYY/MM/DD',
	locale: 'vi-VN',
	supported_locales: ['en-US', 'ja-JP', 'vi-VN'],
	currency: 'VND',
}

let order = {
	account_id: 'acqsulrowbxiugvginhw',
	id: '211562',
	shipping: {
		address: {
			account_id: 'acqsulrowbxiugvginhw',
			user_id: 'usrefmjqwhamyjktbqghd',
			id: 'adrejufuonskkmksvpci',
			fullname: 'Mrs. Kiều Thanh',
			email: 'thanh@gmail.com',
			phone: '0364821895',
			street: '222 Khương Trung',
			district: 'Thanh Xuân',
			region: 'Hà Nội',
			created: 1638353944390,
			created_by: 'agqygncqpyaxoujpfc',
			updated: 1638353944390,
			updated_by: 'agqygncqpyaxoujpfc',
		},
	},
	note: 'Không dùng túi bóng để bảo vệ môi trường',
	due_date: 1638348497687,
	status: 'new',
	payment_status: 'unpaid',
	created: 1638348498737,
	created_by: 'agqygncqpyaxoujpfc',
	updated: 1638353997344,
	updated_by: 'agqygncqpyaxoujpfc',
	items: [
		{
			quantity: 1,
			product: {
				account_id: 'acqsulrowbxiugvginhw',
				id: '2110082',
				product_group_id: '2110082',
				left_product_id: '2110082',
				right_product_id: '2110082',
				url: 'https://baohanhone.com/products/man-hinh-apple-watch-s8',
				name: 'Màn Hình Apple Watch S8',
				i18n_name: {
					vi_VN: 'Màn Hình Apple Watch S8',
				},
				created: 1637912799523,
				updated: 1637912799523,
				created_by: 'agqsulrowbxilyzhds',
				updated_by: 'agqsulrowbxilyzhds',
				image: 'https://vcdn.subiz-cdn.com/file/firegqzhvpwbzdudkxfd_acqsulrowbxiugvginhw',
				images: ['https://vcdn.subiz-cdn.com/file/firegqzhvpwbzdudkxfd_acqsulrowbxiugvginhw'],
				visibility: 'published',
				sku: 'dienthoainew_5265',
				price: 6490000,
				stock: 84,
			},
			total: 6490000,
			fpv_total: 6490000195584,
		},
		{
			quantity: 1,
			product: {
				account_id: 'acqsulrowbxiugvginhw',
				id: '2110080',
				product_group_id: '2110080',
				left_product_id: '2110080',
				right_product_id: '2110080',
				url: 'https://baohanhone.com/products/apple-watch-series-4-duoc-nang-cap-nhu-the-nao-so-voi-watch-series-3',
				name: 'Apple Watch Series 4 Được Nâng Cấp Như Thế Nào so Với Watch Series 3',
				i18n_name: {
					vi_VN: 'Apple Watch Series 4 Được Nâng Cấp Như Thế Nào so Với Watch Series 3',
				},
				created: 1637912799446,
				updated: 1637912799446,
				created_by: 'agqsulrowbxilyzhds',
				updated_by: 'agqsulrowbxilyzhds',
				image: 'https://vcdn.subiz-cdn.com/file/firegqoaunmehylnqfts_acqsulrowbxiugvginhw',
				images: ['https://vcdn.subiz-cdn.com/file/firegqoaunmehylnqfts_acqsulrowbxiugvginhw'],
				visibility: 'published',
				sku: 'apple_2159',
				price: 3200000,
				stock: 9,
			},
			total: 3200000,
			fpv_total: 3199999934464,
		},
	],
	subtotal: 9690000,
	fpv_subtotal: 9689999867904,
	total: 9690000,
	fpv_total: 9689999867904,
	pos_id: 'psreakoakjggfhlibtu',
	channel: 'subiz',
	channel_touchpoint: 'localhost',
	releated_conversations: ['csrefmjrutfizfnzev'],
	user: {
		id: 'usrefmjqwhamyjktbqghd',
		attributes: [
			{key: 'created', datetime: '2021-11-24T09:37:25Z'},
			{key: 'fullname', text: 'Mrs. Kiều Thanh'},
			{key: 'phones', text: '0364821895'},
			{key: 'emails', text: 'thanh@gmail.com'},
		],
		lead_owners: ['agqygncqpyaxoujpfc'],
	},
	currency_rate: 1,
}

template.update(
	acc,
	order,
	{
		primary_color: 'black',
		secondary_color: 'black',
	},
	'vi-VN',
)

template.mount(document.getElementById('app'))
